--建表,主键，非空，默认值，外键
CREATE TABLE TEST_DEPT
(
  ID NUMBER(10) PRIMARY KEY,
  NAME VARCHAR2(20) NOT NULL
)
COMMENT ON TABLE TEST_DEPT IS '部门信息';
COMMENT ON COLUMN TEST_DEPT.NAME IS '部门名称';

CREATE TABLE TEST_USER
(
  ID NUMBER(10) PRIMARY KEY,
  NAME VARCHAR2(20) NOT NULL,
  STATE NUMBER(1) DEFAULT 0,
  CREATE_DATE DATE,
  DEPT_NO NUMBER(10)
)

COMMENT ON TABLE TEST_USER IS '用户信息';
COMMENT ON COLUMN TEST_USER.NAME IS '用户名';

select * from dual;
